package vite.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import vite.data.entity.UserAccount;

import vite.data.dao.UserAccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userAccountDaoConfig;

    private final UserAccountDao userAccountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userAccountDaoConfig = daoConfigMap.get(UserAccountDao.class).clone();
        userAccountDaoConfig.initIdentityScope(type);

        userAccountDao = new UserAccountDao(userAccountDaoConfig, this);

        registerDao(UserAccount.class, userAccountDao);
    }
    
    public void clear() {
        userAccountDaoConfig.clearIdentityScope();
    }

    public UserAccountDao getUserAccountDao() {
        return userAccountDao;
    }

}
